#!/bin/bash

source /home/pavan-kumar/bash_scripts/check_linux_distribution.sh
source /home/pavan-kumar/bash_scripts/install_package.sh 

dist_name=$(check_fetch_distribution_name)
echo "${dist_name}"

# journalctl is a powerful tool used to query and view logs generated by the systemd-journald service in Linux-based systems. It plays a crucial role in troubleshooting and debugging applications because of its ability to provide detailed and centralized logging. Here’s why journalctl is particularly useful for checking application errors:

# 1. Centralized Log Management
	# journalctl collects logs from various sources such as:
		# System processes.
		# User applications.
		# Kernel messages.
	# This centralization eliminates the need to check multiple log files in different locations.
# 2. Access to Logs for Applications Managed by systemd
	# Applications started as systemd services generate logs that are captured automatically by journalctl.
	#

# Check if journalctl is available
if ! journalctl --version &> /dev/null
then
	echo "Error: journalctl is not available on this system."
	choice=$(confirm_package_instllation) "journalctl"
	if choice
	then
		case "${dist_name,,}" in 
			"ubuntu" | "debian")
				sudo apt install -y journalctl
				echo "journalctl installed."
				;;
			"rhel" | "centos" | "fedora" | "rocky" | "almalinux")
				sudo yum install -y journalctl
				echo "journalctl installed."
				;;
		esac
	fi
fi

# Prompt the user for the application name
read -p "Enter the application name to check for errors: " app_name

# Check logs for the application and show the latest 20 error messages
journalctl -t "${app_name}" -p err -n 20 --no-pager


